imagePullSecrets: []

image:
  repository: nicholasjackson/fake-service
  tag: v0.26.2
  pullPolicy: IfNotPresent

frontend:
  name: "frontend"
  message: "Hello from frontend!"
  serverType: "http"
  logLevel: "debug"
  port: 9090

backend:
  name: "backend"
  message: "Hello from backend!"
  serverType: "http"
  logLevel: "debug"
  port: 9091
  errorRate: 0

ingress-nginx:
  enabled: true
  controller:
    service:
      type: NodePort
      nodePorts:
        http: 30080
  ingressClassResource:
    default: true
