apiVersion: embeddedcluster.replicated.com/v1beta1
kind: Config
spec:
  version: 2.0.0+k8s-1.30
  roles:
    controller:
      name: management
      labels:
        management: "true"
    custom:
      - name: app
        labels:
          app: "true"
