apiVersion: kots.io/v1beta1
kind: Application
metadata:
  name: fake-service
spec:
  title: Fake Services
  icon: https://www.shareicon.net/data/256x256/2016/05/16/766096_zoo_512x512.png
  minKotsVersion: 1.122.0
  statusInformers:
    - deployment/frontend
    - deployment/backend
  additionalImages:
    - curlimages/curl:latest