apiVersion: kots.io/v1beta2
kind: HelmChart
metadata:
  name: fake-service
spec:
  chart:
    name: fake-service
    chartVersion: 0.3.0
  values:
    image:
      registry: '{{repl HasLocalRegistry | ternary LocalRegistryHost "proxy.replicated.com" }}'
      repository: '{{repl HasLocalRegistry | ternary LocalRegistryNamespace "" }}/nicholasjackson/fake-service'
      pullSecrets:
      - name: '{{repl ImagePullSecretName }}'
    frontend:
      name: repl{{ ConfigOption "frontend_name" }}
      message: repl{{ ConfigOption "frontend_message" }}
      logLevel: repl{{ ConfigOption "frontend_log_level" }}
    backend:
      name: repl{{ ConfigOption "backend_name" }}
      message: repl{{ ConfigOption "backend_message" }}
      logLevel: repl{{ ConfigOption "backend_log_level" }}
