apiVersion: embeddedcluster.replicated.com/v1beta1
kind: Config
spec:
  version: 2.18.1+k8s-1.34
  roles:
    controller:
      name: management
      labels:
        management: "true"
    custom:
      - name: app
        labels:
          app: "true"
  unsupportedOverrides: {}