apiVersion: kots.io/v1beta1
kind: Config
metadata:
  name: fake-service
spec:
  groups:
    - name: Global settings
      title: Global settings
      description: Global settings
      items:
        - name: hostname
          title: Hostname
          type: text
          required: false
    - name: Frontend settings
      title: Frontend settings
      description: Frontend settings
      items:
        - name: message
          title: Message
          type: text
          required: true
          default: Hello from frontend!
        - name: logLevel
          title: Log level
          type: radio
          default: debug
          items:
            - name: debug
              title: Debug
            - name: info
              title: Info
            - name: warn
              title: Warn
            - name: error
              title: Error
            - name: trace
              title: Trace
    - name: Backend settings
      title: Backend settings
      description: Backend settings
      items:
        - name: message
          title: Message
          type: text
          required: true
          default: Hello from backend!
        - name: logLevel
          title: Log level
          type: radio
          default: debug
          items:
            - name: debug
              title: Debug
            - name: info
              title: Info
            - name: warn
              title: Warn
            - name: error
              title: Error
            - name: trace
              title: Trace
