apiVersion: kots.io/v1beta1
kind: Config
metadata:
  name: fake-service
spec:
  groups:
    - name: example_group
      title: First Group
      items:
      - name: http_enabled
        title: HTTP Enabled
        type: bool
        default: "0"
    - name: example_group_2
      title: Second Group
      when: false
      items:
      - name: key
        title: Key
        type: textarea
      - name: hostname
        title: Hostname
        type: text  
    - name: example_group_3
      title: Third Group
      items:
      - name: email-address
        title: Email Address
        type: text  
      - name: password_text
        title: Password
        type: password
        value: '{{repl RandomString 10}}'     