apiVersion: v1
kind: Service
metadata:
  name: {{ include "fake-service.backend.name" . }}
  labels: {{- include "fake-service.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: backend
      protocol: TCP
      name: backend
  selector:
    {{- include "fake-service.backend.selectorLabels" . | nindent 4 }}
