apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "fake-service.name" . }}-ingress
spec:
  ingressClassName: nginx
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ include "fake-service.frontend.name" . }}
            port:
              number: 80
