{{- if and (hasKey .Values "global") (hasKey .Values.global "replicated") (hasKey .Values.global.replicated "dockerconfigjson") -}}
{{- if .Values.global.replicated.dockerconfigjson -}}
apiVersion: v1
kind: Secret
metadata:
  name: replicated-pull-secret
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ .Values.global.replicated.dockerconfigjson | quote }}
{{- end -}}
{{- end -}}