name: create-replicated-channel-by-branch

on:
  create:
    branches:

jobs:
  create-replicated-channel:
    runs-on: ubuntu-latest
    # Only run this job when a branch is created (not a tag)
    if: github.event.ref_type == 'branch'
    
    steps:
      - name: Get branch name
        id: branch-name
        run: echo "BRANCH_NAME=${{ github.event.ref }}" >> $GITHUB_OUTPUT
      
      - name: Call Replicated API
        env:
          APP_ID: ${{ secrets.REPLICATED_APP_ID }}
          API_TOKEN: ${{ secrets.REPLICATED_API_TOKEN }}
        run: |
          curl --request POST \
            --url "https://api.replicated.com/vendor/v3/app/${APP_ID}/channel" \
            --header "Authorization: ${API_TOKEN}" \
            --header 'accept: application/json' \
            --header 'content-type: application/json' \
            --data "{\"name\":\"${{ steps.branch-name.outputs.BRANCH_NAME }}\"}"